### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by Abel1802** [ZeweiChu/PyTorch-Course#1]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-12-cc82b8fbedcc> in <module>
     11 
     12             if USE_CUDA:
---> 13                 input_labels = input_labels.cuda()
     14                 pos_labels = pos_labels.cuda()
     15                 neg_labels = neg_labels.cuda()

RuntimeError: CUDA error: out of memory

**Comment by ZeweiChu** [comment]
Where is this error coming from? Can you reduce the batch size or change the hyper parameters to make the model smaller?

**Comment by Abel1802** [comment]
thanks for your reply！
I followed the code on your tutorial(no modification).But it went wrong while training the model(in the follow picture).I first use cuda with gpu on my lab. So I don't how to resolve this bug.

At 2019-11-17 14:19:19, "Zewei Chu" <notifications@github.com> wrote:


Where is this error coming from? Can you reduce the batch size or change the hyper parameters to make the model smaller?

**Comment by Abel1802** [comment]
At 2019-11-17 14:19:19, "Zewei Chu" <notifications@github.com> wrote:


Where is this error coming from? Can you reduce the batch size or change the hyper parameters to make the model smaller?

**Comment by ZeweiChu** [comment]
Where is the picture you mentioned in your reply?

**Comment by Abel1802** [comment]
I have solved this problem.But I am also grateful to you! Have a happy life! Good-bye!

At 2019-11-20 16:16:31, "Zewei Chu" <notifications@github.com> wrote:


Where is the picture you mentioned in your reply?
